name: OCaml CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    name: Build Dune application
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        ocaml-compiler: ["4.11.0", "4.12.0", "5.1.0", "5.1.1"]
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # ratchet:actions/checkout@v4
      - name: Set up OCaml
        uses: ocaml/setup-ocaml@35a993375d51ca2dafcd2d8647716b7bb20bc37d # ratchet:ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
      - name: Install dependencies
        run: opam install --deps-only --locked ./devoir_de_programmation.opam
      - name: Build
        run: opam exec -- dune build
      - name: Test
        run: opam exec -- dune runtest
  fmt:
    name: Format Dune application
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # ratchet:actions/checkout@v4
      - name: Set up OCaml
        uses: ocaml/setup-ocaml@35a993375d51ca2dafcd2d8647716b7bb20bc37d # ratchet:ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.12.0
      - name: Install dependencies
        run: opam install --deps-only --locked ./devoir_de_programmation.opam
      - name: Format
        run: ocamlformat --check bin/*.ml lib/*.ml test/*.ml
